accounts:
  - name: ppenter
    coins: ["100000000000000000000aphoton"]
  - name: muayymo
    coins: ["5000000000000aphoton"]
validator:
  name: ppenter
  staked: "100000000000000000000aphoton"
# faucet:
#   name: bob 
#   coins: ["10aphoton"]
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
build:
  binary: "atmosd"
init:
  home: "$HOME/.atmosd"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "atmosd_3000-1"
  app_state:
    staking:
      params:
        bond_denom: "aphoton"
    mint:
      params:
        mint_denom: "aphoton"
    crisis:
      constant_fee:
        denom: "aphoton"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "aphoton"
    evm:
      params:
        evm_denom: "aphoton"
